# Generated by Django 5.0.3 on 2024-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='product_name',
            new_name='book_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='product_description',
        ),
        migrations.AddField(
            model_name='store',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
