# Generated by Django 5.0.3 on 2024-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_name_store_book_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='store',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
    ]
