# Generated by Django 5.0.3 on 2024-04-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_image_store_page_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Book',
        ),
    ]
